const $=s=>document.querySelector(s);const state={status:null,repos:[],tags:[],repo:null,repoPage:1,tagPage:1,selected:new Map(),query:""};
const esc=s=>String(s??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const bytes=n=>{if(!n)return"0 B";let u=["B","KB","MB","GB","TB"],i=Math.min(Math.floor(Math.log(n)/Math.log(1024)),4);return`${(n/1024**i).toFixed(i?1:0)} ${u[i]}`};
const date=s=>s?new Intl.DateTimeFormat(undefined,{dateStyle:"medium"}).format(new Date(s)):"Never";
async function api(url,options={}){let res=await fetch(url,{...options,headers:{"Content-Type":"application/json",...(options.headers||{})}});if(res.status===204)return null;let data=await res.json().catch(()=>({error:res.statusText}));if(!res.ok)throw new Error(data.error||res.statusText);return data}
function toast(msg){let el=$("#toast");el.textContent=msg;el.classList.remove("hidden");setTimeout(()=>el.classList.add("hidden"),3500)}
function notice(msg=""){$("#notice").textContent=msg;$("#notice").classList.toggle("hidden",!msg)}
async function loadStatus(){try{state.status=await api("/api/status");$("#statusDot").classList.toggle("ok",state.status.configured);$("#statusLabel").textContent=state.status.configured?"Connected":"Not connected";$("#statusDetail").textContent=state.status.configured?state.status.dockerNamespace:"Kubernetes Secret";if(state.status.configured){$("#username").value=state.status.username||"";$("#namespace").value=state.status.dockerNamespace||"";loadRepos()}else showView("settings")}catch(e){notice(e.message)}}
function loading(el,n=5){el.innerHTML=Array.from({length:n},()=>'<div class="skeleton"></div>').join("")}
async function loadRepos(page=1){state.repoPage=page;loading($("#repoList"));notice();try{let q=new URLSearchParams({page,pageSize:50});if(state.query)q.set("q",state.query);let data=await api("/api/repositories?"+q);state.repos=data.results||[];$("#repoCount").textContent=`${data.count} total`;renderRepos();renderPager($("#repoPager"),page,data.count,50,loadRepos)}catch(e){$("#repoList").innerHTML='<div class="empty">Could not load repositories.</div>';notice(e.message)}}
function renderRepos(){let list=state.repos.filter(r=>!state.query||r.name.toLowerCase().includes(state.query));$("#repoList").innerHTML=list.length?list.map(r=>`<div class="repo ${state.repo===r.name?'active':''}" data-repo="${esc(r.name)}"><div><strong>${esc(r.name)}</strong><p>${esc(r.description||"No description")}</p></div><div class="repo-meta">${r.is_private?'Private':'Public'}<br>${date(r.last_updated)}</div></div>`).join(""):'<div class="empty">No repositories found.</div>';document.querySelectorAll(".repo").forEach(el=>el.onclick=()=>selectRepo(el.dataset.repo))}
async function selectRepo(name){state.repo=name;state.tagPage=1;renderRepos();$("#tagTitle").textContent=name;await loadTags()}
async function loadTags(page=1){if(!state.repo)return;state.tagPage=page;loading($("#tagList"),7);try{let data=await api(`/api/repositories/${encodeURIComponent(state.repo)}/tags?page=${page}&pageSize=100`);state.tags=data.results||[];$("#tagCount").textContent=`${data.count} total`;renderTags();renderPager($("#tagPager"),page,data.count,100,loadTags)}catch(e){$("#tagList").innerHTML='<div class="empty">Could not load tags.</div>';notice(e.message)}}
function visibleTags(){return state.tags.filter(t=>!state.query||t.name.toLowerCase().includes(state.query)||state.repo.toLowerCase().includes(state.query))}
function renderTags(){let tags=visibleTags();$("#tagList").innerHTML=tags.length?tags.map(t=>{let key=`${state.repo}\0${t.name}`,platforms=[...new Set((t.images||[]).map(i=>`${i.os}/${i.architecture}`))].join(", ");return`<label class="tag-row"><input class="tag-check" type="checkbox" data-tag="${esc(t.name)}" ${state.selected.has(key)?'checked':''}><span class="tag-name">${esc(t.name)}</span><small class="platform">${esc(platforms||"—")}</small><small class="date">${date(t.tag_last_pushed||t.last_updated)}</small><small>${bytes(t.full_size)}</small></label>`}).join(""):'<div class="empty big">No tags match this filter.</div>';document.querySelectorAll(".tag-check").forEach(el=>el.onchange=()=>toggleTag(el.dataset.tag,el.checked));syncSelectAll()}
function toggleTag(name,checked){let t=state.tags.find(x=>x.name===name),key=`${state.repo}\0${name}`;if(checked)state.selected.set(key,{repository:state.repo,tag:name,size:t?.full_size||0});else state.selected.delete(key);updateSelection();syncSelectAll()}
function syncSelectAll(){let tags=visibleTags();$("#selectAll").checked=tags.length>0&&tags.every(t=>state.selected.has(`${state.repo}\0${t.name}`));$("#selectAll").indeterminate=tags.some(t=>state.selected.has(`${state.repo}\0${t.name}`))&&!$("#selectAll").checked}
function updateSelection(){let items=[...state.selected.values()];$("#selectionBar").classList.toggle("hidden",!items.length);$("#selectedCount").textContent=`${items.length} tag${items.length===1?'':'s'} selected`;$("#selectedSize").textContent=bytes(items.reduce((n,x)=>n+x.size,0))}
function renderPager(el,page,total,size,fn){let pages=Math.ceil(total/size);if(pages<2){el.innerHTML="";return}el.innerHTML=`<button class="secondary" ${page<=1?'disabled':''}>←</button><span class="muted">Page ${page} of ${pages}</span><button class="secondary" ${page>=pages?'disabled':''}>→</button>`;let b=el.querySelectorAll("button");b[0].onclick=()=>fn(page-1);b[1].onclick=()=>fn(page+1)}
function showView(view){document.querySelectorAll(".nav").forEach(n=>n.classList.toggle("active",n.dataset.view===view));$("#imagesView").classList.toggle("hidden",view!=="images");$("#settingsView").classList.toggle("hidden",view!=="settings");$("#pageTitle").textContent=view==="images"?"Images":"Connection"}
document.querySelectorAll(".nav").forEach(n=>n.onclick=()=>showView(n.dataset.view));
$("#credentials").onsubmit=async e=>{e.preventDefault();let btn=e.submitter;btn.disabled=true;$("#formMessage").textContent="Validating with Docker Hub…";try{await api("/api/credentials",{method:"PUT",body:JSON.stringify({username:$("#username").value,token:$("#token").value,dockerNamespace:$("#namespace").value})});$("#token").value="";$("#formMessage").textContent="Connection saved securely.";toast("Docker Hub connected");await loadStatus();showView("images")}catch(err){$("#formMessage").textContent=err.message}finally{btn.disabled=false}};
$("#disconnect").onclick=async()=>{if(!confirm("Remove the Docker Hub credentials from the Kubernetes Secret?"))return;try{await api("/api/credentials",{method:"DELETE"});location.reload()}catch(e){toast(e.message)}};
$("#search").oninput=e=>{state.query=e.target.value.trim().toLowerCase();clearTimeout(window.searchTimer);window.searchTimer=setTimeout(()=>{renderTags();loadRepos(1)},250)};
$("#refresh").onclick=()=>{loadRepos(state.repoPage);if(state.repo)loadTags(state.tagPage)};
$("#selectAll").onchange=e=>{visibleTags().forEach(t=>toggleTag(t.name,e.target.checked));renderTags()};
$("#clearSelection").onclick=()=>{state.selected.clear();updateSelection();renderTags()};
$("#openDelete").onclick=()=>{let items=[...state.selected.values()];$("#dialogCount").textContent=`${items.length} tag${items.length===1?'':'s'}`;$("#deletePreview").innerHTML=items.slice(0,30).map(x=>`${esc(x.repository)}:<strong>${esc(x.tag)}</strong>`).join("<br>")+(items.length>30?`<br>…and ${items.length-30} more`:"");$("#confirmText").value="";$("#confirmDelete").disabled=true;$("#deleteDialog").showModal()};
$("#confirmText").oninput=e=>$("#confirmDelete").disabled=e.target.value!=="DELETE";
$("#confirmDelete").onclick=async e=>{e.preventDefault();let btn=e.currentTarget,items=[...state.selected.values()].map(({repository,tag})=>({repository,tag}));btn.disabled=true;btn.textContent="Deleting…";try{let out=await api("/api/delete",{method:"POST",body:JSON.stringify({items,confirm:"DELETE"})}),failed=out.results.filter(x=>!x.deleted);out.results.filter(x=>x.deleted).forEach(x=>state.selected.delete(`${x.repository}\0${x.tag}`));$("#deleteDialog").close();updateSelection();await loadTags(state.tagPage);toast(failed.length?`${items.length-failed.length} deleted, ${failed.length} failed`:`${items.length} tags deleted`);if(failed.length)notice(failed.map(x=>`${x.repository}:${x.tag} — ${x.error}`).join(" · "))}catch(err){toast(err.message)}finally{btn.textContent="Delete permanently";btn.disabled=false}};
let theme=localStorage.getItem("theme")||(matchMedia("(prefers-color-scheme:dark)").matches?"dark":"light");document.documentElement.dataset.theme=theme;$("#theme").onclick=()=>{theme=theme==="dark"?"light":"dark";document.documentElement.dataset.theme=theme;localStorage.setItem("theme",theme)};
loadStatus();

